[package]
name = "three-sum-closest"
version = "0.1.0"
authors = ["Shinji Tanaka <shinji.tanaka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "three_sum_closest"
path = "lib.rs"